비밀번호 재설정 구현 전, 클린코드 규칙에 따라 AuthController, AuthService 리팩토링
washcarnewcar/api.washcar.me-spring-server pull request #45
Opened 2023-04-10 04:02 UTC by UniM0cha

## 🔥 관련 이슈

없음

## 📝 작업 상세 설명

- "함수는 하나의 역할만 해야한다." 라는 클린코드 규칙에 따라 AuthController와 AuthService를 리팩토링 해봤습니다.
- 기존에는 login, signup 메소드 안에 "로그인 관련" 이라는 명목하에 코드를 작성했는데, 클린코드 규칙을 보며 다시 생각하여 작성해보았습니다.

## ⭐ 리뷰 요구 사항

한가지 의문점이 있는데, 현재 수정한것과 같이 컨트롤러에서 서비스를 호출하게 되면 Transaction 처리가 의도한 대로 잘 동작하는지 궁금합니다.

2023-04-11 08:43 UTC, gilteunchoi requested changes
아직 리뷰를 다 보지는 못 했는데,
```JAVA
throw new BusinessException(BusinessError.MEMBER_TELEPHONE_NOT_MATCH);
```
에서 새로 만드신 BusinessError가 소스코드에 추가가 안 되어있습니다.

2023-04-11 09:55 UTC, gilteunchoi requested changes
말씀하신  Transactional내용을 확인해봤는데, 이야기해주신 대로, Transactional이 authService의 각 메소드에서는 작동하지만, 컨트롤러 메소드 전체에서는 적용이 안 됩니다. 따라서 두 개 이상의 서비스 메소드가 Transaction이어야 하는 지금 상황에서는 로직 실행을 컨트롤러에 두면 안 됩니다.

 예를 들어 AuthController의 Signup메소드에서, register() 이후에 cleanSignupPin()에 Exception을 일으켜봤는데, member DB에는 추가가 되지만, pin은 지워지지 않고, 500 internal Server Error를 반환합니다.

따라서 Service단에서 현재 로직을 그대로 가지고 있는 public transactional 메소드를 만들어서, 그 곳으로 로직을 전부 옮겨야 합니다.

참고로, `TransactionSynchronizationManager.isActualTransactionActive();` 을 통해서 Transactional 유무를 확인할 수 있습니다.

리펙터링 취지는 좋은 것 같습니다!

2023-04-11 10:02 UTC, UniM0cha commented
시간이 부족해서 자세히 못알아봤는데 정말 감사합니다!
그러면 어쩔 수 없이 모든 로직을 담고 있는 서비스 메소드 하나를 만들어야하는걸까요..

2023-04-19 13:25 UTC, UniM0cha commented
- AuthService에 컨트롤러에서 호출되어 서비스 로직을 수행하는 메소드들을 정의했습니다.
- 수정된 파일이 많아보이는데, 저희 코딩 스타일 대로라면 탭이 아니라 띄어쓰기를 써야했는데, 탭으로 사용된 곳들이 좀 있어서 띄어쓰기로 변환시켰습니다

2023-04-19 14:32 UTC, gilteunchoi approved these changes
전반적인 네이밍 변경도 그렇고 (PIN 등등) 이야기해주신 비밀번호 재설정 파트 네이밍 좋습니다! 
문장 길게 가져가도 설명이 명확해져서 오히려 좋은 것 같아요

PR한번에 검토하기가 조금 양이 많긴 했는데, 이번 경우는 리팩토링이라서 이렇게 되는 게 당연한 것 같긴 합니다. (space -> tab 바꾼 것 때문이기도 하구요) 테스트 돌려보고, 핵심 로직만 눈으로 따라가긴 했는데 제가 놓친 부분이 있을 것 같기는 하네요

수고 많으셨습니다!

2023-04-20 06:19 UTC, merged

2023-04-20 06:19 UTC, UniM0cha commented on src/main/java/me/washcar/wcnc/domain/auth/controller/AuthController.java
> +@RequestMapping("/v2/auth")
리뷰 감사합니다!